package me.henning1004.addsomefurniture.furniture;

import me.henning1004.addsomefurniture.AddSomeFurniture;
import me.henning1004.addsomefurniture.blocks.Barstool;
import me.henning1004.addsomefurniture.blocks.Flower;
import me.henning1004.addsomefurniture.blocks.FlowerBox;
import me.henning1004.addsomefurniture.blocks.PsychoChair;
import me.henning1004.addsomefurniture.blocks.PsychoTable;
import me.henning1004.addsomefurniture.blocks.PsychoThrone;
import me.henning1004.addsomefurniture.blocks.SimpleChair;
import me.henning1004.addsomefurniture.blocks.QuestionMark;
import me.henning1004.addsomefurniture.blocks.Tv;
import me.henning1004.addsomefurniture.blocks.Worktop;
import me.henning1004.addsomefurniture.blocks.Lamp;
import me.henning1004.addsomefurniture.blocks.LampOn;
import me.henning1004.addsomefurniture.blocks.NeonLamp;
import me.henning1004.addsomefurniture.blocks.NeonLampOn;
import me.henning1004.addsomefurniture.blocks.Carpet;

public class Blocks {
	
	public static Barstool woodenbarstool;
	public static Barstool stonebarstool;
	public static SimpleChair woodsimplechair;
	public static SimpleChair stonesimplechair;
	public static PsychoTable woodtable;
	public static PsychoTable irontable;
	public static PsychoTable goldtable;
	public static PsychoTable obsidiantable;
	public static PsychoTable stonetable;
	public static PsychoChair woodchairN;
	public static PsychoChair woodchairS;
	public static PsychoChair woodchairW;
	public static PsychoChair woodchairE;
	public static PsychoChair ironchairN;
	public static PsychoChair ironchairS;
	public static PsychoChair ironchairW;
	public static PsychoChair ironchairE;
	public static PsychoChair goldchairN;
	public static PsychoChair goldchairS;
	public static PsychoChair goldchairW;
	public static PsychoChair goldchairE;
	public static PsychoThrone woodthroneN;
	public static PsychoThrone woodthroneS;
	public static PsychoThrone woodthroneW;
	public static PsychoThrone woodthroneE;
	public static PsychoThrone ironthroneN;
	public static PsychoThrone ironthroneS;
	public static PsychoThrone ironthroneW;
	public static PsychoThrone ironthroneE;
	public static PsychoThrone goldthroneN;
	public static PsychoThrone goldthroneS;
	public static PsychoThrone goldthroneW;
	public static PsychoThrone goldthroneE;
	public static Tv tvS;
	public static Tv tvN;
	public static Tv tvW;
	public static Tv tvE;
	public static Worktop obsidianworktop;
	public static Worktop ironworktop;
	public static Worktop goldworktop;
	public static Worktop stoneworktop;
	public static Worktop craftingworktop;
	public static Worktop woodenworktop;
	public static Lamp lamp;
	public static LampOn lampon;
	public static NeonLamp neonlampS;
	public static NeonLamp neonlampW;
	public static NeonLampOn neonlampSon;
	public static NeonLampOn neonlampWon;
	public static NeonLamp neonlampSred;
	public static NeonLamp neonlampWred;
	public static NeonLampOn neonlampSonred;
	public static NeonLampOn neonlampWonred;
	public static NeonLamp neonlampSblue;
	public static NeonLamp neonlampWblue;
	public static NeonLampOn neonlampSonblue;
	public static NeonLampOn neonlampWonblue;
	public static NeonLamp neonlampSgreen;
	public static NeonLamp neonlampWgreen;
	public static NeonLampOn neonlampSongreen;
	public static NeonLampOn neonlampWongreen;
	public static PsychoThrone leatherthroneN;
	public static PsychoThrone leatherthroneS;
	public static PsychoThrone leatherthroneW;
	public static PsychoThrone leatherthroneE;
	public static Carpet carpetblack;
	public static Carpet carpetred;
	public static Carpet carpetdarkgreen;
	public static Carpet carpetbrown;
	public static Carpet carpetblue;
	public static Carpet carpetpurple;
	public static Carpet carpetcyan;
	public static Carpet carpetlightgrey;
	public static Carpet carpetgrey;
	public static Carpet carpetpink;
	public static Carpet carpetlightgreen;
	public static Carpet carpetyellow;
	public static Carpet carpetlightblue;
	public static Carpet carpetmagenta;
	public static Carpet carpetorange;
	public static Carpet carpetwhite;
	public static FlowerBox flowerbox1N;
	public static FlowerBox flowerbox1S;
	public static FlowerBox flowerbox1W;
	public static FlowerBox flowerbox1E;
	public static Flower blueflower;
	public static Flower whiterose;
	public static QuestionMark qmark;

	public static void registerBlocks(AddSomeFurniture plugin) 
	{
		woodtable = new PsychoTable(plugin, "WoodTable", new int[]{0,0,0,0,0,0});
		irontable = new PsychoTable(plugin, "IronTable", new int[]{16,17,18,0,0,0});
		goldtable = new PsychoTable(plugin, "GoldTable", new int[]{32,33,34,0,0,0});
		obsidiantable = new PsychoTable(plugin, "ObsidianTable", new int[]{80,81,82,0,0,0});
		stonetable = new PsychoTable(plugin, "StoneTable", new int[]{48,49,50,0,0,0});
		woodchairN = new PsychoChair(plugin, "WoodChair.n", new int[]{0,1,2,3,4,5}, "N");
		woodchairS = new PsychoChair(plugin, "WoodChair.s", new int[]{0,1,2,3,4,5}, "S");
		woodchairW = new PsychoChair(plugin, "WoodChair.w", new int[]{0,1,2,3,4,5}, "W");
		woodchairE = new PsychoChair(plugin, "WoodChair.e", new int[]{0,1,2,3,4,5}, "E");
		ironchairN = new PsychoChair(plugin, "IronChair.n", new int[]{16,17,18,19,20,21}, "N");
		ironchairS = new PsychoChair(plugin, "IronChair.s", new int[]{16,17,18,19,20,21}, "S");
		ironchairW = new PsychoChair(plugin, "IronChair.w", new int[]{16,17,18,19,20,21}, "W");
		ironchairE = new PsychoChair(plugin, "IronChair.e", new int[]{16,17,18,19,20,21}, "E");
		goldchairN = new PsychoChair(plugin, "GoldChair.n", new int[]{32,33,34,35,36,37}, "N");
		goldchairS = new PsychoChair(plugin, "GoldChair.s", new int[]{32,33,34,35,36,37}, "S");
		goldchairW = new PsychoChair(plugin, "GoldChair.w", new int[]{32,33,34,35,36,37}, "W");
		goldchairE = new PsychoChair(plugin, "GoldChair.e", new int[]{32,33,34,35,36,37}, "E");
		woodthroneN = new PsychoThrone(plugin, "WoodThrone.n", new int[]{0,1,2,3,4,5}, "N");
		woodthroneS = new PsychoThrone(plugin, "WoodThrone.s", new int[]{0,1,2,3,4,5}, "S");
		woodthroneW = new PsychoThrone(plugin, "WoodThrone.w", new int[]{0,1,2,3,4,5}, "W");
		woodthroneE = new PsychoThrone(plugin, "WoodThrone.e", new int[]{0,1,2,3,4,5}, "E");
		ironthroneN = new PsychoThrone(plugin, "IronThrone.n", new int[]{16,17,18,19,20,21}, "N");
		ironthroneS = new PsychoThrone(plugin, "IronThrone.s", new int[]{16,17,18,19,20,21}, "S");
		ironthroneW = new PsychoThrone(plugin, "IronThrone.w", new int[]{16,17,18,19,20,21}, "W");
		ironthroneE = new PsychoThrone(plugin, "IronThrone.e", new int[]{16,17,18,19,20,21}, "E");
		goldthroneN = new PsychoThrone(plugin, "GoldThrone.n", new int[]{32,33,34,35,36,37}, "N");
		goldthroneS = new PsychoThrone(plugin, "GoldThrone.s", new int[]{32,33,34,35,36,37}, "S");
		goldthroneW = new PsychoThrone(plugin, "GoldThrone.w", new int[]{32,33,34,35,36,37}, "W");
		goldthroneE = new PsychoThrone(plugin, "GoldThrone.e", new int[]{32,33,34,35,36,37}, "E");
		woodsimplechair = new SimpleChair(plugin, "Simple WoodChair", new int[] {0,1,2,0,0,0});
		woodenbarstool = new Barstool(plugin, "WoodenBarstool", new int[]{0,1,2,0,0,0});
		stonesimplechair = new SimpleChair(plugin, "Simple StoneChair", new int[] {48,49,50,0,0,0});
		stonebarstool = new Barstool(plugin, "StonBarstool", new int[]{48,49,50,0,0,0});
		tvN = new Tv(plugin, "Tv.n", new int[]{0,1,2,0,0,0}, "N");
		tvS = new Tv(plugin, "Tv.s", new int[]{0,1,2,0,0,0}, "S");
		tvW = new Tv(plugin, "Tv.w", new int[]{0,1,2,0,0,0}, "W");
		tvE = new Tv(plugin, "Tv.e", new int[]{0,1,2,0,0,0}, "E");	
		craftingworktop = new Worktop(plugin, "CraftingWorktop", new int[]{0,1,0,0,0,0});
		ironworktop = new Worktop(plugin, "IronWorktop", new int[]{16,17,0,0,0,0});
		goldworktop = new Worktop(plugin, "GoldWorktop", new int[]{32,33,0,0,0,0});
		stoneworktop = new Worktop(plugin, "StoneWorktop", new int[]{48,49,0,0,0,0});
		woodenworktop = new Worktop(plugin, "WoodenWorktop", new int[]{64,65,0,0,0,0});
		obsidianworktop = new Worktop(plugin, "ObsidianWorktop", new int[]{80,81,0,0,0,0});
		lamp = new Lamp(plugin, "Lamp", new int[]{16,17,18,0,0,0});
		lampon = new LampOn(plugin, "LampOn", new int[]{16,17,18,0,0,0});
		neonlampS = new NeonLamp(plugin, "Neon Lamp.s", new int[]{32,33,0,0,0,0}, "S");
		neonlampW = new NeonLamp(plugin, "Neon Lamp.w", new int[]{32,33,0,0,0,0}, "W");
		neonlampSon = new NeonLampOn(plugin, "Neon Lamp.s.on", new int[]{32,33,0,0,0,0}, "S");
		neonlampWon = new NeonLampOn(plugin, "Neon Lamp.w.on", new int[]{32,33,0,0,0,0}, "W");
		leatherthroneN = new PsychoThrone(plugin, "LeatherThrone.n", new int[]{96,97,98,99,100,101}, "N");
		leatherthroneS = new PsychoThrone(plugin, "LeatherThrone.s", new int[]{96,97,98,99,100,101}, "S");
		leatherthroneW = new PsychoThrone(plugin, "LeatherThrone.w", new int[]{96,97,98,99,100,101}, "W");
		leatherthroneE = new PsychoThrone(plugin, "LeatherThrone.e", new int[]{96,97,98,99,100,101}, "E");
		neonlampSred = new NeonLamp(plugin, "Red Neon Lamp.s", new int[]{36,37,0,0,0,0}, "S");
		neonlampWred = new NeonLamp(plugin, "Red Neon Lamp.w", new int[]{36,37,0,0,0,0}, "W");
		neonlampSonred = new NeonLampOn(plugin, "Red Neon Lamp.s.on", new int[]{36,37,0,0,0,0}, "S");
		neonlampWonred = new NeonLampOn(plugin, "Red Neon Lamp.w.on", new int[]{36,37,0,0,0,0}, "W");
		neonlampSblue = new NeonLamp(plugin, "Blue Neon Lamp.s", new int[]{38,39,0,0,0,0}, "S");
		neonlampWblue = new NeonLamp(plugin, "Blue Neon Lamp.w", new int[]{38,39,0,0,0,0}, "W");
		neonlampSonblue = new NeonLampOn(plugin, "Blue Neon Lamp.s.on", new int[]{38,39,0,0,0,0}, "S");
		neonlampWonblue = new NeonLampOn(plugin, "Blue Neon Lamp.w.on", new int[]{38,39,0,0,0,0}, "W");
		neonlampSgreen = new NeonLamp(plugin, "Green Neon Lamp.s", new int[]{34,35,0,0,0,0}, "S");
		neonlampWgreen = new NeonLamp(plugin, "Green Neon Lamp.w", new int[]{34,35,0,0,0,0}, "W");
		neonlampSongreen = new NeonLampOn(plugin, "Green Neon Lamp.s.on", new int[]{34,35,0,0,0,0}, "S");
		neonlampWongreen = new NeonLampOn(plugin, "Green Neon Lamp.w.on", new int[]{34,35,0,0,0,0}, "W");
//		carpetblack = new Carpet(plugin, "Black Carpet", new int[]{48,49,0,0,0,0});
//		carpetred = new Carpet(plugin, "Red Carpet", new int[]{64,64,0,0,0,0});
//		carpetdarkgreen = new Carpet(plugin, "Dark Green Carpet", new int[]{128,129,0,0,0,0});
//		carpetbrown = new Carpet(plugin, "Brown Carpet", new int[]{240,241,0,0,0,0});
//		carpetblue = new Carpet(plugin, "Blue Carpet", new int[]{176,177,0,0,0,0});
//		carpetpurple = new Carpet(plugin, "Purple Carpet", new int[]{192,193,0,0,0,0});
//		carpetcyan = new Carpet(plugin, "Cyan Carpet", new int[]{160,161,0,0,0,0});
//		carpetlightgrey = new Carpet(plugin, "Light Grey Carpet", new int[]{16,17,0,0,0,0});
//		carpetgrey = new Carpet(plugin, "Grey Carpet", new int[]{32,33,0,0,0,0});
//		carpetpink = new Carpet(plugin, "Pink Carpet", new int[]{224,225,0,0,0,0});
//		carpetlightgreen = new Carpet(plugin, "Light Green Carpet", new int[]{112,113,0,0,0,0});
//		carpetyellow = new Carpet(plugin, "Yellow Carpet", new int[]{96,97,0,0,0,0});
//		carpetlightblue = new Carpet(plugin, "Light Blue Carpet", new int[]{144,145,0,0,0,0});
//		carpetmagenta = new Carpet(plugin, "Magenta Carpet", new int[]{208,209,0,0,0,0});
//		carpetorange = new Carpet(plugin, "Orange Carpet", new int[]{80,81,0,0,0,0});
//		carpetwhite = new Carpet(plugin, "White Carpet", new int[]{0,1,0,0,0,0});
		flowerbox1N = new FlowerBox(plugin, "Flower Box.n", new int[]{48,49,50,53,54,0}, "N");
		flowerbox1S = new FlowerBox(plugin, "Flower Box.s", new int[]{48,49,50,51,52,0}, "S");
		flowerbox1W = new FlowerBox(plugin, "Flower Box.w", new int[]{48,49,50,51,53,0}, "W");
		flowerbox1E = new FlowerBox(plugin, "Flower Box.e", new int[]{48,49,50,52,54,0}, "E");
		blueflower = new Flower(plugin, "Blue Flower", new int[]{54,0,0,0,0,0});
		whiterose = new Flower(plugin, "White Rose", new int[]{53,0,0,0,0,0});
		qmark = new QuestionMark(plugin, "Question mark", new int[]{65,65,64,64,0,0}, "N");

	}

}



